# Docker Compose configuration for a multi-service application.
# Defines three services: front, kitchen, and a MySQL database.
# The front and kitchen services build from specified directories,
# expose ports 5000 and 5001 respectively, and connect to the same database.
# The database service uses MySQL 5.7 and initializes with specific credentials.
# A named volume 'vidly' is used for persistent database storage.
# healthcheck makes sure database is up an ready before called

version: "3.8"
services:
  front:
    build: ./orders
    ports:
      - 5000:5000
    environment:
      - DB_URL=mysql://root:password@db/burger
    depends_on:
      db:
        condition: service_healthy

  kitchen:
    build: ./kitchen
    ports:
      - 5001:5001
    environment:
      - DB_URL=mysql://root:password@db/burger
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: burger
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports: 
      - 3307:3306
    volumes:
      - vidly:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "db"]
      interval: 15s
      timeout: 10s
      retries: 5

volumes:
  vidly:

